version: "3.9"
services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - internal

  qdrant:
    image: qdrant/qdrant:v1.9.1
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    networks:
      - internal
 
  mcp-memory:
    build: ./user_memory
    ports:
      - "8200:8000"
    networks:
      - internal

  mcp-tools:
    build: ./mcp_home_memory_cached
    ports:
      - "8100:8000"
    networks:
      - internal

  rag-glue:
    build: ./rag_glue
    ports:
      - "8000:8000"
    networks:
      - internal
    volumes:
      - ./mcp_home_memory_cached:/app/ha_tools

  tabbyapi:
    image: tabbyapi:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "5000:5000"
    networks:
      - internal
    volumes:
      - tabby_models:/app/models
    environment:
      - CONFIG_PATH=/app/config.yml
      - API_KEYS_PATH=/app/api_keys.yml

  # Other services like mongo, qdrant, rag-server, librechat go here
  rag-server:
    image: your-org/rag-service:latest
    environment:
      - VECTOR_DB_URL=http://qdrant:6333
      - DOC_STORE_URL=http://mongo:27017
    depends_on:
      - qdrant
      - mongo
    networks:
      - internal

  librechat:
    image: ghcr.io/danny-avila/librechat:main
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat
      - QDRANT_URL=http://qdrant:6333
      - RAG_SERVER_URL=http://rag-server:8000
      - TABBY_API_URL=http://tabbyapi:5000
    ports:
      - "3080:3080"
    networks:
      - internal
volumes:
  tabby_models:

networks:
  internal:
    driver: bridge
